# data.py
monthly_sales = [
    {"Month": "January", "Total Sales": 385, "Revenue": 12000},
    {"Month": "February", "Total Sales": 410, "Revenue": 13000},
    {"Month": "March", "Total Sales": 450, "Revenue": 14500},
    {"Month": "April", "Total Sales": 470, "Revenue": 15500},
    {"Month": "May", "Total Sales": 520, "Revenue": 17000},
    {"Month": "June", "Total Sales": 550, "Revenue": 18000},
    {"Month": "July", "Total Sales": 580, "Revenue": 19000},
    {"Month": "August", "Total Sales": 600, "Revenue": 20000},
    {"Month": "September", "Total Sales": 630, "Revenue": 21000},
    {"Month": "October", "Total Sales": 650, "Revenue": 22000},
    {"Month": "November", "Total Sales": 700, "Revenue": 24000},
    {"Month": "December", "Total Sales": 750, "Revenue": 25000},
]

individual_sales = {
    "January": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 120, "Revenue": 3600},
        {"Item Name": "Taro Milk Tea", "Units Sold": 90, "Revenue": 2700},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 75, "Revenue": 2250},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 60, "Revenue": 1800},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 40, "Revenue": 1200},
        {"Item Name": "Thai Milk Tea", "Units Sold": 55, "Revenue": 1650},
    ],
    "February": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 130, "Revenue": 3900},
        {"Item Name": "Taro Milk Tea", "Units Sold": 95, "Revenue": 2850},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 80, "Revenue": 2400},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 65, "Revenue": 1950},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 50, "Revenue": 1500},
        {"Item Name": "Thai Milk Tea", "Units Sold": 60, "Revenue": 1800},
    ],
    "March": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 140, "Revenue": 4200},
        {"Item Name": "Taro Milk Tea", "Units Sold": 100, "Revenue": 3000},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 85, "Revenue": 2550},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 75, "Revenue": 2250},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 60, "Revenue": 1800},
        {"Item Name": "Thai Milk Tea", "Units Sold": 70, "Revenue": 2100},
    ],
    "April": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 150, "Revenue": 4500},
        {"Item Name": "Taro Milk Tea", "Units Sold": 110, "Revenue": 3300},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 90, "Revenue": 2700},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 80, "Revenue": 2400},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 65, "Revenue": 1950},
        {"Item Name": "Thai Milk Tea", "Units Sold": 75, "Revenue": 2250},
    ],
    "May": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 160, "Revenue": 4800},
        {"Item Name": "Taro Milk Tea", "Units Sold": 120, "Revenue": 3600},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 100, "Revenue": 3000},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 85, "Revenue": 2550},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 70, "Revenue": 2100},
        {"Item Name": "Thai Milk Tea", "Units Sold": 80, "Revenue": 2400},
    ],
    "June": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 170, "Revenue": 5100},
        {"Item Name": "Taro Milk Tea", "Units Sold": 130, "Revenue": 3900},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 110, "Revenue": 3300},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 90, "Revenue": 2700},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 75, "Revenue": 2250},
        {"Item Name": "Thai Milk Tea", "Units Sold": 85, "Revenue": 2550},
    ],
    "July": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 180, "Revenue": 5400},
        {"Item Name": "Taro Milk Tea", "Units Sold": 140, "Revenue": 4200},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 120, "Revenue": 3600},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 100, "Revenue": 3000},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 80, "Revenue": 2400},
        {"Item Name": "Thai Milk Tea", "Units Sold": 90, "Revenue": 2700},
    ],
    "August": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 190, "Revenue": 5700},
        {"Item Name": "Taro Milk Tea", "Units Sold": 150, "Revenue": 4500},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 130, "Revenue": 3900},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 110, "Revenue": 3300},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 90, "Revenue": 2700},
        {"Item Name": "Thai Milk Tea", "Units Sold": 100, "Revenue": 3000},
    ],
    "September": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 200, "Revenue": 6000},
        {"Item Name": "Taro Milk Tea", "Units Sold": 160, "Revenue": 4800},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 140, "Revenue": 4200},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 120, "Revenue": 3600},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 100, "Revenue": 3000},
        {"Item Name": "Thai Milk Tea", "Units Sold": 110, "Revenue": 3300},
    ],
    "October": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 210, "Revenue": 6300},
        {"Item Name": "Taro Milk Tea", "Units Sold": 170, "Revenue": 5100},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 150, "Revenue": 4500},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 130, "Revenue": 3900},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 110, "Revenue": 3300},
        {"Item Name": "Thai Milk Tea", "Units Sold": 120, "Revenue": 3600},
    ],
    "November": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 220, "Revenue": 6600},
        {"Item Name": "Taro Milk Tea", "Units Sold": 180, "Revenue": 5400},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 160, "Revenue": 4800},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 140, "Revenue": 4200},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 120, "Revenue": 3600},
        {"Item Name": "Thai Milk Tea", "Units Sold": 130, "Revenue": 3900},
    ],
    "December": [
        {"Item Name": "Classic Milk Tea", "Units Sold": 230, "Revenue": 6900},
        {"Item Name": "Taro Milk Tea", "Units Sold": 190, "Revenue": 5700},
        {"Item Name": "Matcha Milk Tea", "Units Sold": 170, "Revenue": 5100},
        {"Item Name": "Brown Sugar Milk Tea", "Units Sold": 150, "Revenue": 4500},
        {"Item Name": "Strawberry Milk Tea", "Units Sold": 130, "Revenue": 3900},
        {"Item Name": "Thai Milk Tea", "Units Sold": 140, "Revenue": 4200},
    ]
}